name: app_tcc
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0
  google_nav_bar: ^5.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/Carregamento.jpg
    - assets/Caua_Banner.jpg
    - assets/Caua_Perfil.jpg
    - assets/Controle1.png
    - assets/Controle2.png
    - assets/Controle3.png
    - assets/Controle4.png
    - assets/Davi_Banner.jpg
    - assets/Davi_Perfil.jpg
    - assets/Fase_1.jpg
    - assets/Fase_2.jpg
    - assets/Fase_3.jpg
    - assets/Fase_4.jpg
    - assets/Fase_5.jpg
    - assets/Fernanda_Banner.jpg
    - assets/Fernanda_Perfil.jpg
    - assets/Ferramenta1.png
    - assets/Ferramenta2.png
    - assets/Ferramenta3.png
    - assets/Ferramenta4.png
    - assets/Gabriel_Banner.jpg
    - assets/Gabriel_Perfil.jpg
    - assets/Logo_Emp.png
    - assets/Logo_jogo.png
    - assets/Pedro_Banner.png
    - assets/Pedro_Perfil.png
    - assets/Pedro_Projeto1.png
    - assets/Pedro_Projeto2.png
    - assets/Pedro_Projeto3.png
    - assets/Pedro_Projeto4.png
    - assets/Personagem1.png
    - assets/Personagem2.png
    - assets/Personagem3.png
    - assets/Personagem4.png
    - assets/Ruan_Banner.jpg
    - assets/Ruan_Perfil.jpg
    - assets/hq_capa.png
    - assets/hq_contracapa.jpeg
    - assets/hq_page_1.jpeg 
    - assets/hq_page_2.jpeg 
    - assets/hq_page_3.jpeg 
    - assets/hq_page_4.jpeg 
    - assets/hq_page_5.jpeg 
    - assets/hq_page_6.jpeg 
    - assets/hq_page_7.jpeg 
    - assets/hq_page_8.jpeg 
